### ISSUE TITLE
raspberry pi 4: apt fails with "Sub-process https received a segmentation fault"

### ISSUE THREAD

**Issue by arlotito** [microsoft/do-client#25] opened 2021-04-14 13:29 UTC
Hi,
I installed the DO client on a raspberry pi 4 with raspberry OS 32bit (which is based on a Debian 10) using the debian10-arm32 packages from the artifacts as follows:
```
apt-get install ./deliveryoptimization-agent/debian10-arm32-release/deliveryoptimization-agent_0.4.0_armhf.deb
apt-get install ./deliveryoptimization-sdk/debian10-arm32-release/libdeliveryoptimization_0.4.0_armhf.deb
apt-get install ./deliveryoptimization-plugin-apt/debian10-arm32-release/deliveryoptimization-plugin-apt_0.2.0_armhf.deb
```

The installation goes fine without warnings or error.

However, apt-get does not work anymore and it fails as follows:
```
root@raspberrypi:/home/pi# apt-get update
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received a segmentation fault.
```

Any ideas? Thanks!

**Comment by jimson-msft** [comment] 2021-04-22 22:14
Hi @arlotito - to fix apt-get, you can consider uninstalling the plugin:

apt-get remove deliveryoptimization-plugin-apt

This is unexpected, I'll leave the issue open and revisit once we have more engineering resources

**Comment by SillyKeith** [comment] 2022-07-19 00:53
We hit this too.  From the do-agent logs, it appears the {GetHost} is returning my IoT Hub domain name and overwriting the correct ubuntu source list.

```
2022-07-19T00:27:05.4968525Z 7948  7952           {GetHost} Returning MCC host: [**---my iot hub domain---**] for original host: [us.archive.ubuntu.com]
2022-07-19T00:27:05.4968612Z 7948  7952  info     {_UpdateConnectionTypeAndGetUrl} 040e59e2-a6cc-424d-bf68-71f76ccfa279, connection type: 1, numAttempts: 1, url: http://**---my iot hub domain name--**-/ubuntu/dists/bionic-security/restricted/i18n/by-hash/SHA256/b70f67be66800195bcaff6e758ae3108ee009022d055925ff2faefe7c25123b8?cacheHostOrigin=us.archive.ubuntu.com
```

**Comment by shishirb-MSFT** [comment] 2022-07-19 18:51
Closing since we have not reproduced the segfault during recent development and not received more reports from outside either.
@SillyKeith Feel free to open a new issue since your case is about HTTP redirection.

**Closed by shishirb-MSFT** 2022-07-19 18:51 UTC
